config/routes.rb
Rails.application.routes.draw do
  

  resources :documents

  devise_for :users

  resources :static_pages do
    collection do
      post :import
    end
  end

  root to:              'static_pages#maps'

  get '/static_pages/import'

  post '/static_pages/import' => 'static_pages#import'
  post '/import' => 'static_pages#import'
 

  post 'import' =>      'static_pages#import'

  get 'help'    =>      'static_pages#help'

  get 'about'   =>      'static_pages#about'

  get 'contact' =>      'static_pages#contact'

  get 'maps'    =>      'static_pages#maps'

end

app/models/document.rb
<<<<<<< HEAD
<<<<<<< HEAD
class Document
  include Mongoid::Document
  field :filename, type: String
  field :content_type, type: String
  field :file_contents, type: Binary
=======
class Document < ActiveRecord::Base
=======
class Document
  include Mongoid::Document
>>>>>>> 93531c41c05c01ee21d60fe7a10dd3c28eb71abb
  def self.import(upload)
    name =  upload['datafile'].original_filename
    directory = "public/data"
    
    path = File.join(directory, name)
    
    File.open(path, "wb") { |f| f.write(upload['datafile'].read) }
<<<<<<< HEAD
  ends
>>>>>>> 6e03a6abffbd827f4167831ade86ef720e44b71e
=======
  end
>>>>>>> 93531c41c05c01ee21d60fe7a10dd3c28eb71abb
end

app/models/document1.rb
class Document < ActiveRecord::Base
  def self.import(upload)
    name =  upload['datafile'].original_filename
    directory = "public/data"
    
    path = File.join(directory, name)
    
    File.open(path, "wb") { |f| f.write(upload['datafile'].read) }
  end
end

app/models/static_page.rb
class StaticPage
  include Mongoid::Document
  field :nombre, type: String
  field :datos, type: Integer

  #def self.import(file)
  	#CSV.foreach(file.path, headers: true) do |row|
  		#staticpage = find_by_id(row["id"]) || new
  		 #staticpage.attributes = row.to_hash.slice(*accessible_attributes)
  		 #staticpage.save!
  	#end
  #end
 
 def self.import(file)
      name =  file.original_filename
      directory = 'public/data'
    
      path = File.join(directory, name)
    
      File.open(path, "wb") { |f| f.write(file.read) }
  end

   #def self.import(file)
  	#spreadsheet = Roo::Spreadsheet.open(file.path)
  	#header = spreadsheet.row(1)
  	#(2..spreadsheet.last_row).each do |i|
    	#row = Hash[[header, spreadsheet.row(i)].transpose]
    	#staticpage = find_by(id: row["id"]) || new
    	#staticpage.attributes = row.to_hash
    	#staticpage.save!
  	#end
  #end

  def self.open_spreadsheet(file)
    valor = '['
    begin
        logger.debug 'abriendo fichero'
        directory = 'public/data'
        path = File.join(directory, file)
        spreadsheet = Roo::Spreadsheet.open(path)
        logger.debug 'abierto'
        spreadsheet.sheet(0).each do |r|
          if valor != '['
            valor += ','
          end
          valor += r.to_s
        end
      
    rescue Exception
      
    end

    valor += ']'

    return valor

  end


end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""
  field :name,               type: String
  field :username,           type: String

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?
  before_filter :authenticate_user!

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password) }
  	devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :username, :email, :password, :current_password) }
  end

  def after_sign_in_path_for(resource)
  	maps_path(current_user)
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:filename, :content_type, :file_contents)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_filter :maps
  
  @salida = 'hola'

  def import
    #@import = false;
    #if request.post?
    @document =  StaticPage.import(params[:file])
    respond_to do |format|
      format.js
      format.html { redirect_to :back }
    end
  end

  def home

  end

  def help
  end

  def about
  end

  def contact
  end

  def maps
    
    if(cookies[:file_name])
      logger.debug ("procesando cookie " + cookies[:file_name])
      @salida = StaticPage.open_spreadsheet(cookies[:file_name])
      logger.debug @salida 
    end
  end

  def show
    
    if(cookies[:file_name])
      logger.debug ("procesando cookie " + cookies[:file_name])
      @salida = StaticPage.open_spreadsheet(cookies[:file_name])
      logger.debug @salida 
    end
    respond_to do |format|
      format.js
    end
  end

  def configuracionMapa

  end

  def configuracionEstadistica
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/documents/_form.html.erb
<%= form_for(@document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :filename %><br>
    <%= f.text_field :filename %>
  </div>
  <div class="field">
    <%= f.label :content_type %><br>
    <%= f.text_field :content_type %>
  </div>
  <div class="field">
    <%= f.label :file_contents %><br>
    <%= f.text_field :file_contents %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Documents</h1>

<table>
  <thead>
    <tr>
      <th>Filename</th>
      <th>Content type</th>
      <th>File contents</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.filename %></td>
        <td><%= document.content_type %></td>
        <td><%= document.file_contents %></td>
        <td><%= link_to 'Show', document %></td>
        <td><%= link_to 'Edit', edit_document_path(document) %></td>
        <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document', new_document_path %>

app/views/documents/new.html.erb
<h1>New Document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Filename:</strong>
  <%= @document.filename %>
</p>

<p>
  <strong>Content type:</strong>
  <%= @document.content_type %>
</p>

<p>
  <strong>File contents:</strong>
  <%= @document.file_contents %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-fixed-bottom navbar-default">
	<button type="button" class= "navbar-toggle collapsed" data-target="#footer-collapse" data-toggle="collapse" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
    </button>

	<nav>
	<div class="collapse navbar-collapse" id="footer-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= 'active' if current_page?(contact_path) %>"><%= link_to "Contacto",   contact_path %></li>
        <li class="<%= 'active' if current_page?(about_path) %>"><%= link_to "Acerca de",   about_path %></li>
        <li class="<%= 'active' if current_page?(help_path) %>"><%= link_to "Ayuda",   help_path %></li>
      </ul>
    </div>
    </nav>
</footer>
 

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="navbar-header">
  	<button type="button" class= "navbar-toggle collapsed" data-target="#header-collapse" data-toggle="collapse" aria-expanded="false">
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">Mapas Temáticos </a>
   </div> 

    <div class="collapse navbar-collapse" id="header-collapse">
      <ul class="nav navbar-nav navbar-right">
      	<% if user_signed_in? %>
      	<li style="color: white; padding-top: 20px; margin-right: 20px;">Hola, </li>
      		<li>
      			<div class="btn-group">
      				<button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="margin-top: 7px;">
                <%= if !current_user.name then 
                  current_user.email 
                elsif current_user.username then 
                  current_user.name + " " + current_user.username
                else
                  current_user.name
                end %> 
                <span class="caret"></span>
      				</button>
      				
      				<ul class="dropdown-menu">
      					<li><%= link_to "Mis mapas", maps_path %></li>

      					<li role="separator" class="divider"></li>

      					<li><%= link_to "Datos personales", edit_user_registration_path %></li>

      					<li role="separator" class="divider"></li>

      					<li><%= link_to "Cerrar sesión", destroy_user_session_path %></li>
      				</ul>
      			</div>
      		</li>

      		<%else %>
      			<li class="<%= 'active' if current_page?(new_user_session_path) %>"><%= link_to "Accede", new_user_session_path %></li>

      			<li class="<%= 'active' if current_page?(new_user_registration_path) %>"><%= link_to "Registrate", new_user_registration_path %></li>
			<% end %>
		</ul>
	</div>
</header>









      				
        	

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mapas Temáticos</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "Acerca de") %>
<!DOCTYPE html>
<html>
	<body>
		<div class="container">
			<h1 align="center">Acerca de</h1>
			<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.</p>
			<p>Expetenda tincidunt in sed, ex partem placerat sea, porro commodo ex eam. His putant aeterno interesset at. Usu ea mundi tincidunt, omnium virtute aliquando ius ex. Ea aperiri sententiae duo. Usu nullam dolorum quaestio ei, sit vidit facilisis ea. Per ne impedit iracundia neglegentur. Consetetur neglegentur eum ut, vis animal legimus inimicus id.</p>
			<p>His audiam deserunt in, eum ubique voluptatibus te. In reque dicta usu. Ne rebum dissentiet eam, vim omnis deseruisse id. Ullum deleniti vituperata at quo, insolens complectitur te eos, ea pri dico munere propriae. Vel ferri facilis ut, qui paulo ridens praesent ad. Possim alterum qui cu. Accusamus consulatu ius te, cu decore soleat appareat usu.</p>	
		</div>
	</body>
</html>

app/views/static_pages/configuracionEstadistica.html.erb
<h1>StaticPages#configuracionEstadistica</h1>
<p>Find me in app/views/static_pages/configuracionEstadistica.html.erb</p>

app/views/static_pages/configuracionMapa.html.erb
<h1>StaticPages#configuracionMapa</h1>
<p>Find me in app/views/static_pages/configuracionMapa.html.erb</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contacto") %>
<!DOCTYPE html>
<html>
<head>
</head>
<body>

</body>
</html>

app/views/static_pages/help.html.erb
<% provide(:title, "Ayuda") %>
<!DOCTYPE html>
<html>
	<body>
		<div class="container">
			<h1 align="center">Ayuda</h1>
			<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.</p>
			<p>Expetenda tincidunt in sed, ex partem placerat sea, porro commodo ex eam. His putant aeterno interesset at. Usu ea mundi tincidunt, omnium virtute aliquando ius ex. Ea aperiri sententiae duo. Usu nullam dolorum quaestio ei, sit vidit facilisis ea. Per ne impedit iracundia neglegentur. Consetetur neglegentur eum ut, vis animal legimus inimicus id.</p>

</body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, "Inicio") %>
<!DOCTYPE html>
<html>
<head>
</head>
<body>

</body>
</html>

app/views/static_pages/import.html.erb
<h2>Import Products</h2>
<%= form_tag('static_pages/import', remote: true, :id => "importForm") do |f| %>
  <%= file_field_tag :file %>
  <%= submit_tag  "Import", :id => "importfile"%>
<% end %>

app/views/static_pages/import.js - copia.erb
alert('maps success!');
<% if remotipart_submitted? %>
  alert('submitted via remotipart');
  console.log('submitted via remotipart');
<% else %>
  alert('submitted via native jquery-ujs');
  console.log('submitted via jquery-ujs');
<% end %>

app/views/static_pages/import.js.erb
<% if remotipart_submitted? %>
  console.log('submitted via remotipart');
<% else %>
  console.log('submitted via jquery-ujs');
<% end %>

notificarModal3('Fichero importado satisfactoriamente.');

app/views/static_pages/maps.js.erb
alert('maps success!');
<% if remotipart_submitted? %>
  alert('submitted via remotipart');
  console.log('submitted via remotipart');
<% else %>
  alert('submitted via native jquery-ujs');
  console.log('submitted via jquery-ujs');
<% end %>

app/views/static_pages/show.js.erb
<% if remotipart_submitted? %>
  console.log('submitted via remotipart');
<% else %>
  console.log('submitted via jquery-ujs');
<% end %>

$('#parag').html('<%= @salida %>');
$('#parag').hide();

var tabla = JSON.parse($('#parag').html());

if(tabla.length > 0){
	var cLabels = tabla[0].length - 2;

	//para cada ciudad se crea una tabla para visualizar
	for(var i = 1;i < tabla.length;i++){

		console.log('procesando ' + tabla[i][1]);
		//se geocaliza la region y se agrega un marcador para poner el grafico
		var datosi = [];

		//se obtienen los datos a partir de las etiquetas y del valor asociado a las mismas
		for(var j = 2;j <  tabla[0].length;j++){
			datosi.push([tabla[0][j],tabla[i][j]]);
		}
		
		//se agrega un marcador a esa ciudad con el gráfico correspondiente
		agregarDatoAMapa(tabla[i][1],getChart(datosi));
	}

}